folio-org/ui-servicepoints

index.js
https://issues.folio.org/browse/STCOR-237
=> Do not show service point modal when no sps are present. Part of STCOR-237

index.js, package.json
https://issues.folio.org/browse/STCOR-244
=> Hide service point switching in cases when no service points are present. Part of STCOR-244

translations/ui-servicepoints/de.json, translations/ui-servicepoints/pt_BR.json
=> Update translation strings as of 20180913T150458

translations/ui-servicepoints/hu.json
=> Update translation strings as of 20180924T185314

translations/ui-servicepoints/ca.json, translations/ui-servicepoints/fr_FR.json, translations/ui-servicepoints/hu.json
=> Update translation strings as of 20181004T193841

translations/ui-servicepoints/ar.json
=> Update translation strings as of 20181031T224505

translations/ui-servicepoints/ar.json
=> Update translation strings as of 20181112T151205

translations/ui-servicepoints/pt_PT.json
=> Update translation strings as of 20181212T135930

translations/ui-servicepoints/zh_CN.json
=> Update translation strings as of 20190108T192353

translations/ui-servicepoints/en_SE.json
=> Update translation strings as of 20190110T173959

translations/ui-servicepoints/en_US.json
=> Update translation strings as of 20190130T201814

translations/ui-servicepoints/it_IT.json
=> Update translation strings as of 20190219T224024

translations/ui-servicepoints/es_419.json
=> Update translation strings as of 20190422T163602

translations/ui-servicepoints/it_IT.json
=> Update translation strings as of 20190718T220243

translations/ui-servicepoints/it_IT.json
=> Update translation strings as of 20190729T163855

translations/ui-servicepoints/ar.json
=> Update translation strings as of 20190819T080537

translations/ui-servicepoints/ru.json, translations/ui-servicepoints/zh_TW.json
=> Update translation strings as of 20191014T135140

translations/ui-servicepoints/ja.json
=> Update translation strings as of 20191028T205642

translations/ui-servicepoints/ja.json, translations/ui-servicepoints/ru.json
=> Update translation strings as of 20191111T233434

translations/ui-servicepoints/he.json
=> Update translation strings as of 20191114T012425

translations/ui-servicepoints/it_IT.json
=> Update translation strings as of 20191115T154823

translations/ui-servicepoints/fr_FR.json
=> Update translation strings as of 20191122T140350

translations/ui-servicepoints/fr_FR.json
=> Update translation strings as of 20191125T160504

translations/ui-servicepoints/en_SE.json
=> Update translation strings as of 20191220T210632

translations/ui-servicepoints/ur.json
=> Update translation strings as of 20200210T220102

translations/ui-servicepoints/ja.json
=> Update translation strings as of 20200413T183215

translations/ui-servicepoints/ja.json
=> Update translation strings as of 20200420T134821

translations/ui-servicepoints/zh_TW.json
=> Update translation strings as of 20200424T193712

translations/ui-servicepoints/zh_TW.json
=> Update translation strings as of 20200505T210535

translations/ui-servicepoints/en_SE.json, translations/ui-servicepoints/en_US.json
=> Update translation strings as of 20200527T144757

package.json
This is part of an on-going initiative to completely migrate all of `folio-org` projects from `@bigtest/mirage` to `miragejs`.
[`@bigtest/mirage`](https://github.com/bigtestjs/mirage/) was originally a prototype to make `mirage` available to any framework, but it has since been archived in favor of [`miragejs`](https://miragejs.com/). The documentation for `miragejs` is not only prodigious for its extensive API docs but also for its tutorials and guides. Furthermore, it receives regular bug-fixes and maintenance releases in thanks to its extremely large and active community.
Previous PR: [@folio-org/stripes-erm-components #270](https://github.com/folio-org/stripes-erm-components/pull/270)
_Linking the previous pull request so that subsequent ones can be found tagged below._
<details> …
=> Remove bigtest/miragejs from dev dependencies

translations/ui-servicepoints/es.json, translations/ui-servicepoints/es_419.json, translations/ui-servicepoints/es_ES.json, translations/ui-servicepoints/hi_IN.json, translations/ui-servicepoints/ko.json, translations/ui-servicepoints/zh_TW.json
=> Update translation strings as of 20200922T125348

translations/ui-servicepoints/pl.json
=> Update translation strings as of 20200924T211627

translations/ui-servicepoints/ber.json
=> Update translation strings as of 20201109T135508

CHANGELOG.md, package.json
https://issues.folio.org/projects/UISP/issues/UISP-22
=> UISP-22: Upgrade stripes to v6

CHANGELOG.md, package.json
https://issues.folio.org/browse/UISP-28
=> UISP-28: Increment stripes to v7, react to v17

CHANGELOG.md
https://issues.folio.org/browse/UISP-42
=> Release v6.3.0

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md
https://issues.folio.org/browse/STRIPES-865
=> do not publish 'artifacts' to npm

CHANGELOG.md, PULL_REQUEST_TEMPLATE.md
Add PULL_REQUEST_TEMPLATE.md file to the repository
https://issues.folio.org/browse/UISP-44
=> UISP-44 - Add PULL_REQUEST_TEMPLATE.md file to the repository

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, package.json
[UISP-48](https://issues.folio.org/browse/UISP-48) - Update Node.js to v18 in GitHub Actions
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
=> UISP-48 - Update Node.js to v18 in GitHub Actions

CHANGELOG.md
https://folio-org.atlassian.net/browse/UISP-54
**NOTE:** module version in package.json is already in place. so it is not needed to update it now.
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> Release v7.1.0

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md
[UISP-59](https://folio-org.atlassian.net/browse/UISP-59) - Upgrade version for actions/upload-artifact from v2 to v4
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
=> UISP-59 - Upgrade version for `actions/upload-artifact` from v2 to v4

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UISP-62; https://folio-org.atlassian.net/browse/UISP-63
=> UISP-62, UISP-63: migrate stripes-* deps; react-intl to v7
